"""add wallet_address to user

Revision ID: 01245ad1bf17
Revises: 44c34cbf601b
Create Date: 2025-05-05 18:13:51.386858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01245ad1bf17'
down_revision = '44c34cbf601b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_address', sa.String(length=42), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('wallet_address')

    # ### end Alembic commands ###
