"""Додано верифікацію продавців

Revision ID: ba5daefebe81
Revises: a60875a027a4
Create Date: 2025-05-09 11:44:31.617889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5daefebe81'
down_revision = 'a60875a027a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_document', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tax_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('tax_id')
        batch_op.drop_column('company_name')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('verification_document')

    # ### end Alembic commands ###
